CREATE TABLE Roles
(
    RoleId INTEGER IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(256) NOT NULL,
	NormalizedName NVARCHAR(256) NOT NULL,
    ActiveDirectoryGroupCN NVARCHAR(256) NOT NULL DEFAULT '',
    CONSTRAINT PK_ROLES PRIMARY KEY(RoleId)
);
