CREATE TABLE UserRoles
(
    UserId INTEGER NOT NULL,
    RoleId INTEGER NOT NULL,
	IsActive BIT NOT NULL DEFAULT 0,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY(UserId, RoleId),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY(UserId) REFERENCES Users(UserId),
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY(RoleId) REFERENCES Roles(RoleId)
);
