CREATE TABLE Users
(
    UserId INTEGER IDENTITY(1,1) NOT NULL,
    Username VARCHAR(50) NOT NULL,
    DisplayName VARCHAR(100) NOT NULL,
    ActiveDirectoryGuid UNIQUEIDENTIFIER,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL DEFAULT '',
    Salt VARCHAR(255) NOT NULL DEFAULT '',
    AccountType INTEGER NOT NULL DEFAULT 1,
    IsActive BIT NOT NULL DEFAULT 0,
    TwoFactorEnabled BIT NOT NULL,
	LockoutEnd DATETIMEOFFSET NULL,
	LockoutEnabled BIT NOT NULL,
	AccessFailedCount int NOT NULL DEFAULT 0,
    TwoFactorToken NVARCHAR(MAX) DEFAULT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY(UserId),
    CONSTRAINT UQ_ACTIVE_DIRECTORY_GUID UNIQUE(ActiveDirectoryGuid)
);
